Abolish {combina,estima,sugges,solu,migra}tino{s,} {}tion{}
Abolish accomodoation accomodation
Abolish availabel available
Abolish caputerd captured
Abolish cennoct connect
Abolish cofnig config
Abolish fonud found
Abolish fundoation foundation
Abolish mabye maybe
Abolish ogal goal
Abolish passpharse passphrase
Abolish phares phrase
Abolish shrikning shrinking
Abolish sitll still
Abolish taht that
Abolish teh the
Abolish watned wanted
Abolish wolud would
Abolish woudl would
