# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci_renesas" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "rpool/root";
      fsType = "zfs";
      options = ["zfsutil"];
    };

  boot.initrd.luks.devices."root".device = "/dev/disk/by-uuid/6b14ccda-a493-4d9a-9161-eef943be79ae";
  fileSystems."/etc" =
    { device = "rpool/etc";
      fsType = "zfs";
      options = ["zfsutil"];
    };

  fileSystems."/home/b" =
    { device = "rpool/home_b";
      fsType = "zfs";
      options = ["zfsutil"];
    };

  fileSystems."/var" =
    { device = "rpool/var";
      fsType = "zfs";
      options = ["zfsutil"];
    };

  fileSystems."/nix" =
    { device = "rpool/nix";
      fsType = "zfs";
      options = ["zfsutil"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4A7C-598D";
      fsType = "vfat";
      options = [ "fmask=0137" "dmask=0027" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b10f03bc-e98b-4fa7-ac8e-83103c5f4d38"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
